FROM mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022 AS build-machine
COPY . .
RUN dotnet build -o C:\out C:\src\app.csproj
RUN dotnet dev-certs https --password "changeit" --export-path "C:\out\app.pfx" --format Pfx --verbose

FROM mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-ltsc2022
WORKDIR /bin
COPY --from=build-machine /out/ /bin/
EXPOSE 443
USER "NT AUTHORITY\SYSTEM" 
ENTRYPOINT ["dotnet", "app.dll"]