FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS build-machine
RUN powershell.exe -Command "& { Start-BitsTransfer -Source https://aka.ms/download-jdk/microsoft-jdk-17.0.6-windows-x64.zip -Destination C:\microsoft-jdk-17.0.6-windows-x64.zip }"
RUN powershell.exe -Command "& { Start-BitsTransfer -Source https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M1/bin/apache-tomcat-11.0.0-M1.zip -Destination C:\apache-tomcat-11.0.0-M1.zip }"
RUN powershell.exe -Command "& { Expand-Archive -Path C:\microsoft-jdk-17.0.6-windows-x64.zip -DestinationPath C:\ }"
RUN powershell.exe -Command "& { Expand-Archive -Path C:\apache-tomcat-11.0.0-M1.zip -DestinationPath C:\ }"
RUN powershell.exe -Command "& { (Get-Content C:\apache-tomcat-11.0.0-M1\conf\server.xml) -replace '8080', '80' | Set-Content C:\apache-tomcat-11.0.0-M1\conf\server.xml }"

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019 AS web-machine
COPY --from=build-machine /jdk-17.0.6+10/ /jdk-17.0.6+10/
COPY --from=build-machine /apache-tomcat-11.0.0-M1/ /apache-tomcat-11.0.0-M1/
ENV JAVA_HOME C:\jdk-17.0.6+10
ENV CATALINA_HOME C:\apache-tomcat-11.0.0-M1
ENTRYPOINT ["/apache-tomcat-11.0.0-M1/bin/catalina.bat", "run"]
EXPOSE 80

