FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS build-machine
COPY zulu-8-azure-jre_8.42.0.21-8.0.232-win_x64.zip zulu-8-azure-jre_8.42.0.21-8.0.232-win_x64.zip
COPY apache-tomcat-8.5.47-windows-x64.zip apache-tomcat-8.5.47-windows-x64.zip
RUN powershell.exe -Command "& { Expand-Archive -Path .\apache-tomcat-8.5.47-windows-x64.zip -DestinationPath .\ }"
RUN powershell.exe -Command "& { Expand-Archive -Path .\zulu-8-azure-jre_8.42.0.21-8.0.232-win_x64.zip -DestinationPath .\ }"
RUN powershell.exe -Command "& { (Get-Content .\apache-tomcat-8.5.47\conf\server.xml) -replace '8080', '80' | Set-Content .\apache-tomcat-8.5.47\conf\server.xml }"

FROM mcr.microsoft.com/windows/nanoserver:1809 AS web-machine
COPY --from=build-machine /zulu-8-azure-jre_8.42.0.21-8.0.232-win_x64/ /zulu-8-azure-jre_8.42.0.21-8.0.232/
COPY --from=build-machine /apache-tomcat-8.5.47/ /apache-tomcat-8.5.47/
ENV JAVA_HOME C:\zulu-8-azure-jre_8.42.0.21-8.0.232
ENV CATALINA_HOME C:\apache-tomcat-8.5.47
ENTRYPOINT ["/apache-tomcat-8.5.47/bin/catalina.bat", "run"]
EXPOSE 80